# Salix Game Studio Configuration File

Window:
  title: Salix Game Studio v0.1.0
  width: 1280
  height: 720

Renderer:
  type: OpenGL

Engine:
  initial_state: Editor
  target_fps: 60

GUI:
  type: ImGui
  dialog_width_ratio: 0.7
  dialog_height_ratio: 0.75
  font_scaling: 1.0
  global_dpi_scaling: 1.0

Timer:
  type: SDL